# https://probot.github.io/apps/settings/

allow_squash_merge: true
allow_merge_commit: false
allow_rebase_merge: true
default_branch: main
has_wiki: false

labels:
  - name: 'bug ğŸ'
    color: '#FC2929'
    oldname: bug
  - name: duplicate ğŸ‘¯
    color: '#FBCA04'
    oldname: duplicate
  - name: feature-request ğŸ™ğŸ»
    color: '#FBCA04'
    oldname: enhancement
  - name: github-sponsor â¤ï¸
    color: '#815543'
  - name: needs-more-info ğŸ•µğŸ¼
    color: '#f3ffa8'
  - name: wont-fix ğŸ™…ğŸ¼
    color: '##EDEDED'
