# https://probot.github.io/apps/settings/
labels:
  - name: 'bug ğŸ'
    color: '#FC2929'
    oldname: bug
  - name: duplicate ğŸ‘¯
    color: '#FBCA04'
    oldname: duplicate
  - name: feature-request ğŸ™ğŸ»
    color: '#FBCA04'
    oldname: enhancement
  - name: github-sponsor â¤ï¸
    color: '#815543'
  - name: needs-more-info ğŸ•µğŸ¼
    color: '#f3ffa8'
  - name: not-stale ğŸ”’
    color: '#BFDADC'
  - name: stale ğŸ‘»
    color: '#BFD4F2'
  - name: wont-fix ğŸ™…ğŸ¼
    color: '##EDEDED'
